name: Demo App

on: [push]

jobs:
  build:
    name: Greeting
      # This job runs on Linux
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v1

          - name: Set up JDK 8
            uses: actions/setup-java@v1
            with:
              java-version: 8

          - name: Java Build
            run: mvn clean install

          - name: Docker login
            env:
              DOCKER_USER: ${{ secrets.DOCKER_USER}}
              DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
            run: docker login registry.gitlab.com -u ${DOCKER_USER} -p ${DOCKER_PASS}

          - name: Docker build
            run: docker build -t registry.gitlab.com/catfi8h/demoproject .

          - name: Docker tag
            run: docker tag registry.gitlab.com/catfi8h/demoproject:latest retistry.gitlab.com/catfi8h/demoproject:$(date "+%Y_%m_%d_T_%H_%M_%S_Z")

          - name: Docker list images
            run: docker images

          - name: Docker push
            run: docker push registry.gitlab.com/catfi8h/demoproject